blueprint:
  name: Todoist Battery
  description: |
    File Todoist task for low battery replacement.
  domain: automation
  input:
    battery:
      name: "Battery"
      description: "The battery to monitor."
      selector:
        entity:
          domain: sensor
          device_class: battery

    battery_threshold:
      name: "Threshold"
      description: "The percentage under which the task will be created."
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: box
    window:
      name: "Window"
      description: "How long the battery should be below Threshold before a task is created."
      selector:
        duration:

    todoist_project:
      name: "Todoist Project"
      selector:
        text:
    todoist_labels:
      name: "Todoist Labels"
      description: "Comma (without spaces) separated list of tags (e.g., foo,bar)."
      selector:
        text:
    todoist_priority:
      name: "Todoist Priority"
      description: "A numeric priority where 1 is low priority and 4 is high priority."
      selector:
        number:
          min: 1
          max: 4
    todoist_due_date:
      name: "Todoist Due Date"
      description: "A string representation that would work in todoist for a task."
      selector:
        text: 

trigger:
  - platform: numeric_state
    entity_id: !input battery
    below: !input battery_threshold
    for: !input window

condition: []

action:
  service: todoist.new_task
  data:
    content: Replace {{ trigger.entity_id.friendly_name }}
    project: !input todoist_project
    labels: !input todoist_labels
    priority: !input todoist_priority
    due_date_string: !input todoist_due_date